---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCT8c1grcTot1SEwc6qM1HEDYdGaSWYxToCMGAxAnTwP0MaTdL9xh+DODp5zGV4QbxjGRo2SqjPIiyNu6P1q1KjsT0EIJvCNA+mf6kzgqWqcdjP647ZDwik0Jbk+CESmyKr5KzkGLNGsspWRXs3MScZmfFIZiBfpG+y+Bg+TA5O4q4AbcMl9wvH6FpoyD46Eu5riTWzhQYz5sQQQEvY3jVqyyF2jDfu+8uTbgbyXyPLh5+DKQXpExCjanSSoPmXoSqGe8shcefL80d1bBGrvc4apQHyqOpKRmz74An1cX9XAU9/ALr/0+SNdU47ookMB5XtvPaYmE+sicmRHM1ZJoCdSYCmHf9zIFZt56WVHIs/AJGsXW1FkCzrCfT+zPN3CGXEaW8h+DjuNKRrpBVZ9SKlPO9/039AR4JULA9ZjYZDI2zMPurUVx/QHuCVjKvfvcxnj7gnholsAfUyhItqsWgjnfwEuCezjP71KazVRLN1HsOydGqr87vZMug0WgArED+ATwmxtRsBH7WVKimXqauNvu9C2h7VheywckJMG/wLrJ1LXHeV9LtsjWM5OcgfySXoq5BJZ4uZ7V0liNWqwWFRxvEPUvMOWoxWw/QMypz1Sv2+dAlvujHzp4XbBpgvFaN0LgvnZ/sn+zr3VlehfWmLzqJq6zwMBJcVaQZCO6eiV0PuuJrbgzjvotXwF2X2b7lwnd9YErIdDhcpxPAHcJLSoUxCbevFMf6eceRQMVZEHQ==
    admin-user: AgAqT7QyBxiA5DIAlR8eOfzGT3sJAYrYevBje1rzxwZHRO5Gkc1Sw6pSdS0Rmp85tBJAUmPAOMjoj5FP2NgNuuryBuPnwWLl0LUrITg2GBuXuuG9PitcftEeND/ZtBgEZeuMyR4vA7EqbCVsR4vkX42ZzVy6LZSzvvifLF+GqxPBjULSnTC111VcYi5zVMx8VO6SPoK0A1JOM6EyNHbrzXyfnH4EWdqrPDX8Dc44yTzaScGMMjAAJl87VrEK95o9MVIaqvO4eIKNneICNgHuVdfmO/pvMCcqXIHL5e3fAEiYdCZXgjM1Qx0foRjTK2L/hh1k35AplHJdeqK8u6pAqY0rvlZsw0NgC5sJ195MF+SfE6lnraZ08zNpPm5d5qXl5N4Oq2qfS6oTP325KMVUrjgLfTiu8xUIjOiGmZmuGL5aPoW6AjMDdLieuUjOKsVr+0I16OXmb2/BtV8mYqdihDhWx6FFfb5/ySo6P+umej/rVxY17/baV+sURXq/HrscwvbgjJQYYwog/mTLQHF1pqC7uGxvJwqCjux6bLwunf8L/muWGuhoRXGPrHPEnRhQAcLvkx5iNsc2J5uLPy0ifAk04IbyuPQYFw5mi+8a4NdOaahzQDa06CWMxAX8GdjCoZBaVFMyHJgLVY8yNNsHxhndqONKsxof2heDKpWdFvEvokKBUqTJgOUwx6gfiEysiZ+xxEHU
  template:
    metadata:
      name: admin-secret
      namespace: monitoring
    type: Opaque
