---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBz4avhsKZSuUF3Mi+izz326lBWjvyZ0gdASsX740KpUeAwwV7Y7OCsgE78Xs2G+ribDbEml3tWPy5FvBnFWI9uNOGzBSqRL+Z0upfYcsAgROJ5AKSjEgaAuk/5ZqUUMN7BcDL5eFDEtMjOa9HCLgNZKyFOxKWbUB7lYVU7MiYFmin/4OmWLdWfpEgh/IQV0xL+s8FsZkWlz2IHABPfuSjpT3W6D8lm243JcXHRSziBiypqSdrVJrSrzWlX1HAj6PTJ5Zm1lOEW9n6UW1AxPyftYGVNDOZoxy0RhmjOvi506Jt7KHVKjkzKi2BnWrcKxyTfmHqQIhs6eIXkocJxMkSXh7f9BtoEzGWazQmpO5gEiolqFNoqQUraUJvM3dBpaisjfjbjriFiPy65Lmn7apO0W3i6CD+p/MvnvKZ3BC1jKpdP6M4r+DeCnPqcWzGAdfQRJL+UhexaP8q3bldxCCgfJ+Ft/6nxRlNnGVyG13qVzbg/N1b+tSuOzpgQ4vWy40oahn8zd2zle111q21to70fR176/tsH8uR3SfOmJ3EimW/J6qST6WGV0MYSrgg12mt3CCQviUoKJtvYK/yyogDrL4VhwE/L6NV6R9zQFKAkOmzc9rQauLp2y9hdTYLFdCmo99dgn4qPPkB4FTeI9ey39kdLsO1dFY2Q7lz5hW52/6HAGe5Q64aNgWLifU+s6TrgKVDoS3j/A294NerpD6TpHLG46FkrrNivSimw9f/X3g==
    admin-user: AgCnQZ9eD/zrGxVBNUbWz/+xDWtm8dNlX/M0k82ZaaT2BcgwoMhOG52gOY6Vhz8ooV4MsoDqx7PpV97HswmjjgpMQh4MKIAaMi7OKShQGowIU7xzzz96ke3ls89G/gLNPfh9fMMUSzyEUYamalKyVL5zHU9GENAH6yNqAKPrVNAzb0rEDq70vIonbQOU4bw8SSi4mAy9i9xTiU8VxQfbSVTgl2wE7JEfQpEaQMomKp7DgSvvfxbmQI8I32xwx5a+ttRSIZobjdU+YJ9JF6BKB7wyGqdSsg0Pfump3B8ON6TSvMtK3VJgvntEUqXRSM+EOFhrK0aJpTDmRkN7akbsFdqvsHjvAbh2zPdNeQu+cifnpPWYYAXUYESNurwKp8PnwXCWjqztbC3NImrAHcX6pv0fQBAyfTCYMbKDWh4EIbwzLdfb3GJv2gw+FoCJ1kw36g6dV17FtdlyAJ1mwkpJStHKzGgxPNmYa3LFfTkZsB+Kayj4Hawe1EgyvUy2bk9wxlaUdJzL523YPmNgaFxlTPIF4Y9Dzkt5ejQV5wiaqCgtFa3eJxSxi3Jio1JjenzbV4hb9H9pITs9MP90VMSUAxL5s5dqLoxRJlxUZDTWM/PYgHIs0DZg4zBqQEb3Cjcgu9JzKQddI08Ou4wgDFygOZ1Da8dSBb/VL7FIQFH6N99sgy0BxazsOzcVc1se50VFdd5SLs2y
  template:
    metadata:
      name: admin-secret
      namespace: monitoring
    type: Opaque
