---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgClhf/acYxPudGd5MFonJnHWnLhhIiz//fDr2GYfLFW7M7sRNIYxYi2S2H4md2S+oC8D2yDw8DMx7sEW1rjJQ5tq717Vz0ORX7cBXjBPanzJfDeLfgaEWsMn1o0vGqAvWBKWa37El+nbqZzypX1djCHYqHX8AZgLQ5A4jOnuA4jG/jYPfrOm1Cc+lLGFcuU4Oe3FdsLsRMW+KNo1PNJrTFcics9qNV6lAIt58afCuIPoqkKJNrOpxczAs9NHj3bZ/o2AZhahtuUTH8YZSKtbn/f9jwitCvdZE5UOcE7HGOYBtlWHQM2opQdPWWYV+I7QoWPowPJln5e/Vk5KvTF2SD+ADYYbYsmUSGndCb4qtVB40PT4IEcsCWS2Bve73UDANOe5rf1VeM5nt1eBgd2BY8j9mAVZFfz6SE64PU6D9XfN53YjKpuCJ+QUAjz6M7G5mB129P7pRVvKn7ep6rWx2e/okBnvIGApVdWRGyx2NcWHov7qRUIS4zR8abbCNYfP9DL3GKvMQfDIuFztMeXfpXck5q0LtSG+V1uWH/TcWi/g6aGWSrXzuGTTQ98fmYHzhXRAYJLfIqfy1MFA2bNRMxOerhMm7SzpUINa92LIWvTcl3dE86O6Ko25cBbSaAlum6sRu4Ba1Qt5OEwmQsSiTfnoeHwsKtPmlDGVFtKMD+q2IxPPNsf+uDrHVU6YDy9e/Zoc9shI3Wfw80wW80EniFKaW7tQWp9me/TkCg0VLhU2w==
    admin-user: AgB7uJ8p3r4osw3E8UuuX2+1AjNgQENcSBpWmybZR/yPVOw5FDKTm6b+3sacYoghAu9qmx7RzqnnfVIpCSPXwb5x435HiU6/ikaF1tzH3NThnc9smQMzUjKVl1NtB5bq8vbIE8dGcAex6yfUSiBpXQgaytDXH+CbZn/sQkSskiHHnNBd08uCBl4TabyW6FxXgFcm6vwXrdcn6/w1RMSz/7ge7o24blAH4VDZYfQMvEPvPmL4wcF+nACZzQX89qsBqHO2a14KusiA3RSUrwiT/Zb0vi5VNm3Awtq0cvLJ8VPaiMflvw4ZpZ9uBedWG/vYcgm88c3eNe5rI9jvkdvivFoq1UsJt9TevdEChAtT5SGfGfgsMgbkdOJXN1wdZYwno8ZZtfj3jS8ikEpcaSZAo1NuTVTuTk5oiVGu3gslrL42lDml+KGO2voNkqa4wFa4ifi3lmrSqIrJ6mYAAh+ofIachq9n2IobVu6KruRr4PCXc5DZ7BVEAXZEgIy+n4CJbjqX+MQ1E5Js2W2k/6r899lFTgpIcawRg3w7LRDaOrSlbq039PWaxDYBMV/G/l7or55qCV8i8phUmS5kCsapi1ok3uNGdl9dwJxOSs+2RpG6o3gTQjp0BL7HcvdgqLDOiScD01wLatDIQ/WfG7sNtL2FYjFPtVmgLWX4DbF89VykZy4zQqZDO1OmgSFRWvoOzTKTJiBb
  template:
    metadata:
      name: admin-secret
      namespace: monitoring
