---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgCYtdto+bir+KyNtb87aCIy6+jurztuU0DoUQHpG8P/bQJkO8KGXGKSXV3Z5KzA/BfE+OeiM9q5UBxmUeTKCyPDNSTroXtyrS8td7X7RrCmSJu4UX5CnAWiajyh+6fHvS/WZs33FWpJYmvhsrltB179Sst8E9OnKpWwwci9MPKdqwseaDUpPG/bSEBKxo1xTawtYWPvpFD5TSqoPBuCpe9d2//QDCKzRg9x95fL30UqLELzDI3AN7+gCFL5qRsBSqNmNipJT4/EsC22xdadSTC7qXG9mKSk/cf2AfEZcH2J85RcP7ymVxnUs6IyAQ2a5aaH2LTGlVN9Ilugiy4kmmKAH6QBdx+XRMNv/kGxr68Lwqj5ejMg8JgQHhrtileezb36oHWJgfBNh3N2hxRMMAi5P+j3GHccRu4mc+NOWySObPYSgpxTev7NdeTFGoM6jbPt2tu6NhmQTXB0ymZhmUJeCc1K0mXUUvPkEHTcOmc+RfW93DJ07imnr1pXidhlW5is+U23gEPRhJ+LRj9fsLZAbBqjG+nzyqQzD96e47mIWhMLN3s5NRI6BmYhd4s9EZIRx1Z27k7UYtvW+N4P7s8bInGxSR6Lr1kQfsw2lVlv07LxLz2Q3lcudwDgfS3ZdW/NlS8Dy1GyB/pIg35ds1e2eFEj5IcArU/aP0jZmiy91j+wkC61QbnxSuvQ81iLVVxVAa81VpH/qdHXoUWMLYosKx0bd8aHnlc/Wi/IuFFzaAHF2/9Km2hrht6tJ/pw
  template:
    metadata:
      name: alertmanager-telegram-secret
      namespace: monitoring
    type: Opaque
