---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-healthchecks-secret
  namespace: monitoring
spec:
  encryptedData:
    url: AgBk20265I8XBwcL3n8YBwn1aIThlTX2szOHYB55Gz1lRKVFJ/whiO+FnfG74wg8t375x5z+FXuvVNke2MKToWp1OUuf0uVPkfHLuZziAfj3bIwC4xNksvI+/ugjrMO6gVHsYZ6U7xECpK18xvAXW78khmY8duKdzhfEwWOsFgRZQXuWnwDpbvT/mStzau8eraGxQlgSgxzkmJteSkhacZ1AJGCUIKBY9Z/o5euTy2QAR4BW1m6/zQa7gdhcegcFgHrugYVlvcSpJHCyrIHM1b1kuPFw3VtzWwJ+NvPkgebuAz+wPSbOSsCopW1Coj6ONuS9S7Ac4ZpnhODPItWHyQY3IjiOC4YrX8MpYf7xJpf8XE0Ozhtp3juS+QEHxvHniJ0Mn7V3ivrdXtlnblsKwzJVOPMmJMMKoeTQ0Z1ZHIbrPrh2hvX8jnYy2dKNeK3hqhkhVEpfxyeAsFnIlX2WmfdhNbOwVCYqcq2LKccNR73nBTOtdQ9BhgzOTUodUFlN38BK9GUSa2HCXEuNMsvDKFNbQ0H2rdT6CeigIU8Xcl3171K7n2BonSrhY075pOAC41lxHwas59WRRb+2i4krRRiz6WxXqFZq7A6E+GdnlF4+mRUrycsOyEtLysVk4T5sHU9pDj6yAk+0ZxULsDyu4mX07Nw5aXq3r6tzcbyFe0IWEB0rV+9TaaJ/Vy2jDA20BpaCprCNWlXQsD69VYEJmO4f37wzn9hmbrjZyOyQlraTdaK0ZMeMBZPk5xyqghNl5mpSjNAzw7Jopw==
  template:
    metadata:
      name: alertmanager-healthchecks-secret
      namespace: monitoring
