---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-healthchecks-secret
  namespace: monitoring
spec:
  encryptedData:
    url: AgBki0se4Rr0S7naqCQnwO7gsp67wnekS5maRveKDPnK18ISJZ2AKvKKjIvCutlSC9P8KB32dbVolnxlO0h/H4DMu+FJYjxIxgNBn51L/TLlSxW/9XxkF6YTGoWSEXN8bEbEILOXdVNr75AUodvZCFdlfQByqJLjtOaBzMOPONCa3D6BdT/HtV1AMjOlw0B5VKUyhwwbiKPzdizfnn1eKCiujA0uE+0+O1OUIBadlABZbSfZi/aJkEIIfwvLbZ4J4LPQaOXYvrKrfgxKhl9JFqesxhU0sAizy75IbaonUmtLyN0qwqFlmYlm9OODazQq1fAhpBMK0CbOyGcrS3L+uubyqUHa86OECMppOKeaTrZNQ0f5JkYcA2xFKvHp0CYhl8ykfq5NSCA5eMnLryfRoaKrUdJs1L6TKIQ9BaKxcYfitXuOkkIde7C5IT0E0YcZyyBB3M7FqjqpAtp9qUvMC9R199jk+JA6X5IvELdRd7LWmd5dg/VOsF8NypmyrudMb7+GdrL88e+JXm7XRH2Svy/CAZd8wVEQuvdI/xdtyy5s9v/NFpUvX2JbRimNjienU/XUrfSiaUKeaWw9qr8GWdVD1hR+G+CE+eiMZVoDJPEqA7Rhv2y4+AzbCasw0aQrD+8SuleFBbnceLMXfvaSo9ITzjr1LLflfPzI+g0OoWmwBG0np50R74vlWKL9iJtzRQbG1PIZ/57Bch+mGjc+dX+88WUabyYsffWwbEm84QJfUyf2sd/O3i9n76oWlcwTKJYI2+q5vQQe7g==
  template:
    metadata:
      name: alertmanager-healthchecks-secret
      namespace: monitoring
