---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgAeBbXJG5u1bVc+Qr5ho/sGqspkSJfnmxmC1sQp3pClih6K7hTgBv3LfPutlEcOBTl2juPRdGneHSGPxcy3Nm+rgAehU+W+0W869pxgeWtsbLTQhjk348z/Vxh56i7MZ5hVZ2nh7heha8CxJ9aCj66LMlNV8F0H8fESCh1jtu1KjBovy0EGprlx7ecxoCMpspMvsUfuTOn7Dg+dJwjd7Tcp6hiUq/Y3s99CPgg9IsCAC9k9WdgSf2qyv7fA2Yrs4fx0dIP1qsE108tLjkcwY3xFZlw+hDcVzcVEB3V3FMT1VWdiFRil2Tmaf34HH6L8AeXEnGjY0a76TWVEnatUGdId9C+uka5V0t3GYRlMDF8ZEqQhWWr/buuJHJl4zE0bQZAhIs8+o46WtO268X5U7dKfh7V9FBxOEc9OBIBBDVLJsuiVOk0P2rWcD7nM+ALyE2ALH4mVtTI9j8NzL6YjoqpnwD0l2Dg5MgE0ht9BXoq3aW2K/FiLzQWLsA7mtyYV6cpQefLnzAgXMn+pY2lH3ZqE2mKVBrdRGXhs33fDxQDKCrw/4moqS1nQ3KuneMM+Phdbt7aAtCQLA4mVBr0gYdwJ1RlFNRmbwxkq+j/bqETQCUd83y7LJKycnqdvva+MOxUS3LIZGW7/N1oOW6K7a/lZycYjjc+0o6r5m8diRwh658P+HAH82G0OBVdcPRTj7g2EI3cAWVkdfBv8mR2pQ40Xq7nzLbpxyBXg2UAg1OYlqdAxTpB1iQw1CrLY5eXC
  template:
    metadata:
      name: alertmanager-telegram-secret
      namespace: monitoring
