---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-healthchecks-secret
  namespace: monitoring
spec:
  encryptedData:
    url: AgA9767voXP6taMQaJGVwIcowHE5Y3NBMkucaLodimXHNTrlnzpEoVC5Uc9ygY4uVYU3V5VlhI7pGqBmt1Em9BPtHkj/U7zcHs46dMUAsV8K6hw8l4Yt9ybtUmKCv0PwIQwJBeadFKToGInxXwdYCJLbrq/xex434KPTPrC2l8hjPy52pS9DF09RgfzFXdAfQPhi9UuuRdU/H7MYe6oPeWIdtoh06tYjzZoTQM4227+36pk8rXyUFtGIJOEG4H1uCPFIMuisS+t9+hvnrtQplNxRqzCveBrDC+3XeCFJd2OsNv076bQLEp2rGWdE+BBpKKrz4zXQHG7Jq9SMLQZLKPDnxo6bPT/zdDX2zamp8q4qNKpywSGsuDeVX5RG4DhzHgYucaA8grNnoL/uDOeiFbULDDe5I5Qqh1+cWQ35XVTexWODfcB1aQDsb/hvafzUrWSvkd45Z7EbFO8VITrYsS9/xa0YA7AzGZELaIJeeMyxGyN/DkDBftgellhra1o+Ix/uCgdKFc3YM0cX8q6dnAC3aGuZUg/LUUsTcpEESy9k6D3pUxV5OGUXB6tocW7mAysXSz3w/NerYKcwvL6wQlklMnq+gAkV+F52uLBdfGEt/Ulf8w9Xkm2PwHYzByLKi66HoqqU8oG/ClScn1e6UeZ2y1PTLlGZXJq/S3FDKBimUCXDsYpJCsFAQbf9HJsI8JB2BUnmtzlj5tJH2B+sbltugCDt1W4TF/cQNgQPGgrpM+yvCnmoix7tNMzgJu3aqJidslmqJQD+/A==
  template:
    metadata:
      name: alertmanager-healthchecks-secret
      namespace: monitoring
    type: Opaque
