---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgAH/mUgXiwBM4SEteeDRkVZtDWvey8R/7DLZs6er6ZT1hiJkbmiy1oDCdz+4cJa9d0ZQ3Nmzoy9RVWoqyG1uVjx2ZHBDLBkz0EDycN15jZb8/Hz2GHe8npDqS+L7JwdPa7C+k/oxfRLTVxEgmnuWWF0k85v8P6YvCQVEW61tWxfBtXcMumXF0sUbJRh6SehpO5+u/KlQ8mJsRQmbjAvsv07iSX2xNE2mJhSKVa9nzbbZPpd4WRNr+NXG30A6Si7PbxRgFd5Ab73O5wLG9fWqUcI9TKF0t4fZKEDg1BQGfa/UprRqyvQIF8xPI+tnnR7RJ8FAw4Jpnm5eIIOi4L7+SIMuVeimP6WzGjjFCCCwYL2vqCicb9+7aByQq/9IEgms5uevwQTCN28zCYiV3tFcCRJUN6b1wZV56riIwQS0i3hcAiFvwBk/6oK3tqM3mZfW5qXAo9xwzpjfc9ClEpJukUUX8INZPUcbGqD1XVc8z4dfQz5CkV00TRSs+LK69dbP4gaeCNStPoxyIbvZ2R7vV+eOpdY93CCW6rvU1CEEkVhvIeqFXXyxSuKgI6NH3qQPOerHDGVMC3xAD74eDk78TPdxSVco/33G4zujMkeIuS6piOEsjOQm0Tx5HBfvKHLahxQ53Hz9Wme6n4r8BkqtZSEvs7i4i0a7otBTibMImgAVuHR5ZPOwLN5jkcs0WKoeCBc/J4VPxorG4iI737blTxk4VGFMDFF4CBJ7niSQxvB7t1iJYkHD5tmPOEhVp0p
  template:
    metadata:
      name: alertmanager-telegram-secret
      namespace: monitoring
