apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system

resources:
  - namespace.yaml
  - repositories.yaml
  - admin-secret.yaml
  - prometheus-release.yaml
  - loki-release.yaml
  - fluent-bit-release.yaml
