apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-release
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "83.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    cleanPrometheusOperatorObjectNames: true

    grafana:
      enabled: true
      # set admin credentials from Kubernetes Secret
      admin:
        existingSecret: admin-secret
        userKey: admin-user
        passwordKey: admin-password
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 1Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      grafana.ini:
        auth.proxy:
          enabled: true
          header_name: X-authentik-username
          header_property: username
          auto_sign_up: true
          default_role: Admin
        auth:
          signout_redirect_url: https://auth.kschamer.info/application/o/homelab/end-session/
          disable_login_form: true

      additionalDataSources:
        - name: Loki
          uid: loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: false
          jsonData:
            maxLines: 1000

    prometheus:
      service:
        type: ClusterIP
      prometheusSpec:
        retention: 7d
        retentionSize: 6GB
        scrapeInterval: 60s
        evaluationInterval: 60s
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 8Gi
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        resources:
          requests:
            cpu: 300m
            memory: 2Gi
          limits:
            cpu: 1500m
            memory: 4Gi

    kubeProxy:
      enabled: false

    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi

    kube-state-metrics:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
