---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secret
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgA0EDF5FcW1mXL0XcBTHiBxqe4WUX2YL7ft9Jx0hcKWvPLkjq9ro8uoQxYaYlDq6BeaiY3GXxCbs4yowNME1klFLIauP6urR2rwdGCOE5cZDkoFcGK8jQYw8dAI8eMd1hKFI2MJISHy+xK3os+RO2zhsGpCdYPsQn4w2XKWHZbPm+Pmas1DfKPk7DrZpOp5rXKK/rKU0ncEOMjsYxCcUJVD6wiIYOfvF8ay1G+hC1YpTFBJkcWrY4zo5RNt9KV0tHmT/teXc76K06qERDfWbtlCOYJT6N0SI3YHMtdSm8tolWebyUvboH7Wp3EM06rwAD5TmJJje2atbEX3SH6QClxzlJM92sAPxOacYzqXKNNc2ese6OEbUaBL0UzpyZklkkxUzJ3k4K/5ian+80wlSSsxt2ks3FjO8nT9pF7gvAfN3VKkBgzTYXmoi+9xobjg/dcXmR70ga5fWV8gCZ4kgrpm+2mD7AhF48lZNiG0yPLGum/FLHJinJ7ObEoHXn50WcL9Az+ymnu297eKZenZnolnWuG7kbDFP6+dt1Ek555yxrhBHeylmSu6IaDNSq6EKWEBzNfv9BS3bMQOyB4G4yQhPmo5nMswlxiyogj0Sh2dOYqmuZixtC+lyOzKj5Ar9IFaukZ4JnNWjwnM1aQNjZaXLVR3CV/xX7fLM7a+1givVJt82Tel8FJNI64jmqyFA8J0rjk2gd4eaul1r2puR6ZcjJC0VEt+RVbcAj7bvJsTmg==
  template:
    metadata:
      name: siyuan-secret
      namespace: siyuan
