---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secret
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgBOZ9MeBPELh49YRrBm+62BvpmZ5bwbWfLrZaSuQUP38NjocwDtjYi7062xbV/RBGzyL+P2JIQKxhygiYFuOJWK45cA4gI7/m09M0Q5UaPdsOl4B0iYr4+dVMM3uavl1429EdIwwjS+T4KhYOceFddY5F/qASOY+FrAviRVI0EfM+ite+/CdAINUseL40F4SzFvdyezI6rQeF02rE1TKKWqdyFOY158Fj3Ha+i6FNz7TugqBjewuyhKNvfU6fHIqX1GLXBAyUY36CIX73LKrzBV+ubsUHj1YmnW+cmcZfx4VokBSpZH6QCIDc/iA9aSm2N4X34dXS9DOjobfSvwx2oJKNiWurATU7wOuGXgXK92M0OKw4Yd/PeI4oWDw4aTu+TtScDkKgUGuBsvfPNSflb9He12C9kSF6nCJjfjYl+roXFv40OZ3u6NAFA1pcu+au9tbtOc9bX3lYFNorffj+bg845ZD+u1AJsT4S81+Geswvncxl5cdGY2p5Ks5wqxWq1WCMv1ncoxy3y1ozQziahGpB5U24Km92fGb14PrHqbp6BxhrVLAajhgfCRisp9WDTR0W3WqhrqChTFMfAbhs9q44wGlc1AAjmMvDy2Ua8JcUfJM7uiPdey5Rpuze1jJAhUdhaRNx/MN49Ypq1H5HMTWyq8TKN59tAKIC9OHNwhVk6SsGc9zcny8Jr0viCZ1ju8sG8yQwcRRQzOVMUrA81TvwAm7kH46YWEaKKe6zkgaA==
  template:
    metadata:
      name: siyuan-secret
      namespace: siyuan
