---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: siyuan-secret
  namespace: siyuan
spec:
  encryptedData:
    access-auth-code: AgCB1D8v6FkkJZqE8sWrBNTnZR+DCQ1gxxW6B/Q/xG5BlAI3UZOMPbEygIdvKLJ51/g2JeZQFuk/vlrVJC+xDfTSDv7lY8xOxh6SseVXTY69on7fqQIzOQP4HR1dzk8BbRiNIvVqOPk91RSlGxjpbvtB1OSX5Np86LNMM3NtOshduT+jq0sF1cdZsXypYyIut8Bj5Qw4gIA5n7DkmRYRAybN99Vb8/FNSExt39zPEUIAFJwfI4tMQQzO1tAeGTLljLyC+jDhv2DIgLtacCADcubk/yb3dFcPPZiong86xcVE3YF4VBAIlNzCBOYMK/XEM6AgRSzARV8a4I11wpURHulPdx746LEXhgC/kh07hb/WE08T4VgZQ42jsm/NVLXQ14Btgx2wxeiGSFXoKEt0ebN4ZDy4M9cw8tFRdo1xJdN2+rLGrwTTu0QwU5I+8Uth8N4O/wrUPg23Os/4MItpX0vu8LeTR5SrMIphCtYJ5V19fMuDQuUKE81gLnM6xoEqDMl/S7uq9r3+o3wILD6dPu5Hp1LkFobXcoXsZpcAnnL0XqFn7FErnsahWy36V6du8MkMplYVOdv/KyM/EA7H1zy2bZTqzXWndUp4ATLV8DvW9Zsx+U9IorAVIFI1vW2kdE4+pu7JnXeoN4KEn8ROh9k7ZXkf64sCiA7vXGg9QSavsclsiNwnmHTs/IPAIRZ15jQt9Yw6ylQDToittbh5ucyXUr9YqqoSnNpPIovcd33WWQ==
  template:
    metadata:
      name: siyuan-secret
      namespace: siyuan
    type: Opaque
