---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: network-policies
  namespace: flux-system

resources:
  # NOTE: Network policies are disabled for now due to issues with Flux and Hubble
  # They will be redesigned and re-enabled in a future update
  # - clusterwide-policies.yaml
  # - system-policies.yaml
  # - talos-controlplane-1
  # - talos-worker-dmz-1
  # - talos-worker-trusted-1
  # - talos-worker-untrusted-1
  # - talos-worker-monitoring-1
