---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - paperless-sealedsecret.yaml
  - pvc.yaml
  - redis-deployment.yaml
  - deployment.yaml
  - paperless-gpt-deployment.yaml
  - ingress.yaml
  - network-policies.yaml
