---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pv-pihole-config
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pi-hole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pv-pihole-dnsmasq
  resources:
    requests:
      storage: 50Mi
