---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgArLF/pn64sNMTCbIDclpW47jPpUIhXh1eNeG5FDmz7QaYolq171EpCTMp0uYasXeZ9cjh54PP8bsEZQtXocMD07dGshSXYLVIsgeRxQovczu6/uUQJEd1Z0DUh+0XH22MYmGnmfO0U7VFhN40KF3HtrB2DspGbXyfT/cTSlysFKVJj/KDDCF2gT3XHjOOEgFRJ0kDwb5dyScVjzH8xZYbcOlGeB7hRYSHhASnE5wfWwCdFvQePYhDcLddZZqFkITDn0Xt2Om4OJEFoPyQ84+BBWxDoBnUpsZV0/MXP4xEmIbl9haME319TMHznDoSEmbnqNm+dwLcbqAh7x2xMRdCwNbMZ4MzQvO1b5AoIBbNaxM83mF+lO1SsQFbBfRWn4DsQHLdWh+ukpx1kpBb4b7YU5R0V737KV5LvLdsvFEXYpixHAMKoNwasqWXKr/mPdIv31Ku9lE3rUlEZW2peSO9xCD8YUdXZv37hvMmyfxj59sB5lUpzETobNHyUtisaR3SGal8hNDdbiYx/Pz3nEBVdpX/DuCHE4TthH2KR7Hu7fF8/PW/LL2RUGPxZCc5b03Cp5uoY4dHHwIb+C6PlUv+/bL0g+hbL87TtFlsXP8ja8/Kb9Z8qxPWBFcT2Im+XE2kWMoNATmOCciEgHrigAg3JQaKZVS+zTJTTM9XuWG2sYdw4GipPwmt765jVs4Fze1gmY7U8UWOgfybOS/xdfgQ0W7OrFIj58MlJxvo1kYFyCIoNsVl/gx9R2W5E
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
    type: Opaque
