---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgC56rZPNWCF5rJ9TaHRd9eBew3M3NRnTPfTU4xA0Oq5CTIBu3RJO2AUzG/td8elhqBtNvku1r+y1sRi7VRzUjOSN66tDMedywGlwrCwg587dD/fjybXWDf1dwjEHtPPl8MJIxssBsEhy9vXo5IkiYJ5Z6QolSNyxX4trs5LUJmNI51M1vj0DV8/yrUmvjyAWPitGXu1vgL3VvunjmZEd9eFxS3OuKshgZMIlW8goe9aM2mczHp8HhjmzwdLODOGdPUChBmyGWPCTU9vB9qKJRFhkj2GW1ebdLL28sfrjTEpJMZcoOxdmper+9BkmATpDcU9TJ5v7RaR2mO+3NO8CcbTqnW42VAVB5qBS6YVlrSmwRJ9irpf+gG0bGv43oZ+6LeleGCUltOEyf0fmMDsOwYRiprfJMieldQITwLUjpj0T7wwTgjE6B5vRlLIVPnCnvzgyqt0af+nfsl/Dc6QR6dwLuJes48iGHugkSqC2Djeehjz+tiD0NxaME8JG8cBgD1v81deZANTu05UbHMiFC8o+LSYv3YNvgLYUuLIWPLQJ6V5CJJ1AeabKuxZy8E5suo/Srlp4Vorh01WDwHMgGTGfnhRe9+SanX/NjHi7yFL16NKNVPX6WmzAf5Mujlp0KGrSP8RMoE1iY26LEeKBlh+iTNtgke1AW2zG5PhedKyDlnALJkF7qTcoBlaKWmM+R6a/b9YBtj/7VqXqoJx3EK5XYDaDydfFPHbuQgLAMCazVQXw2VwFA==
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
