---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik
spec:
  encryptedData:
    api-key: AgCeEuYolFSFrQAUG0/FDRbJdT0a0deDr7S0WvVC+85WUbbWctpikDbEB91mN61eWJPTkrvdJ0KrHuvHPFdr82VXPyIJ/+E/JzuK1pMq3JscIMd5zDoLLfnjWxocujpgJLoDf21IY37S/r7I9S1l9CBBPBJwgGIx+HrQWVoRTEPElHFrSbYgFBBiEM1w89z3boNgXnPfmRPqo7V7UEamQ+qJ4aMmjOvoqoWGJYAIsZEE/e2a//LegDUOhUr5+vMtc0fNBTkHHINKScOB4Sr3Jfdd3qMW4em2sSSS7RzYQ7V5Cac6RptCfhpxH/sOmXQCngxXtkxPkqsLzWTdnjrjyF3383cZiAZxhEUHkPxTD4sd1kHrEEtrLDOSnOqdh4DwXnHJmfmmlrxb96l+oYtD8Gsv3WBv3vV9jpZYkn1GwPDyJ3tFdGbCa8Ro53yrsBpY05GrVyBG1l+5bslbk4kT0JeTboIcMNmEKtcrOnfMNvItDtt3i5Ei8iineNp/se9pjaIyEumMftnwDNdmmI+cTEh5AJ7H2zqjOkMhe2p63BB2rwa6Dn/Tla6E0LUCr+LxmSHGP6LE8N9G7KQSMwaj62aZ0/fF2yh7su5hC/z6VzOcv+W4A5sdPRpiDX5NDDhN5cZTo6PIRAEi6M1kqWIQTsmGodR6e7OB4Ll+5oP1LgzGkwKzCNyty66UE5vMbVvAqB39AxEIU662MjxabG08ai14T9WKn301b5+QpfFfV6V48Zv5P8f/5jgnFFTS
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik
