apiVersion: v1alpha1
kind: LinkConfig
name: ens18
up: true
addresses:
  - address: 10.10.20.22/24
routes:
  - destination: 192.168.123.0/24
    gateway: 10.10.20.1
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.123.1
  - address: 8.8.8.8
  - address: 1.1.1.1
