---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBZxjvN3QC3cRWo0EwmCZ3xpQ4T3cDZi4jZAFa3JJqZ1U1h1hSW2Jem5sWM0SKtch0NuhXfxmaLtV/DGIf/qv4d4aui/u0rd9DaXJiLhfqo/fGsU7nzXObdeL10i8OoYXjDjOBzJJTc52F2e2Kpuqn3Ob0Xl5vDuUM94lGL3E01cCp+BL+N7J9zRZLCHnSfsqT/UYiJg1iPuKLff8ciHaBOi7lAMzrdslR6VRVuHQ2TNcTTT9DFjb+lJ2O+UlorCNyUfym7We7ONKmowbaK8R5PoqPh2nfOivBcts8VnfeiW61kbK2gC3bYEGKHB8MVcB7GNKwNSlKFSTA5HmWhGNkA3tSUByu18OX4lZ/C65kd++6UIosh/KXJppqj+nuwvmOBBKhZyeol2ZnS8iuNWXeFJjZOa/IoLBNy4oIaTrZbjINxjbFhD6TSmFMYhk6V4cMPUWRdIsylBNIt26LyC+du73OD2MjRaUEEirKlEvgxw5CxZsdOu0UGWuJk0lJyEAoFFI/ctJZFcwRJc3jVWHjZog8c7yAQSYfz0ouWde/ozAvdxN8GpVOBJeYtufmLFn2Q+78mDzpB6v/bo2XIb0SobwUEAXPu5Eby/Xwj4V6nc1FMEw7n9b3Ph35NdHFaYplXK2PEAYyNXbkz8KpplwrEsFurT3DjqEqRTaKfP5pNAI0iF6+DqC3Q8pjk0LsURCneqn7CwIjvyh1eT+djCBvkNZWg8FJsJC0L+jCbjfpf0JBjPWrQOUvmc1/+mrsd8Jw=
    OAUTH_CLIENT_SECRET: AgA/RjesSc7oMuqywgrxfJJ+Wm3NAwDja2FVoVHlRtZ/2tKwWH1cC3ySmt5RkWORATE3GMj6JQLrs0ioqbjY7niIIe6koRTuE2L7+0JG58G0DiTFdhTNImgFo1EE1vXvephT0yfmbBppAm2hu/Svg3GxQammjCTbpHA8b0WSnRUhEyleDV7bb0ik5YEl9LcfWxESZzM9XRBHW/8dJAv54M840fd6H72PGwLq4B0Dodw+DtrRwopOg9AzMJhTuU5hOp2UiqyLWL6ZB6Aime/Cgvseb7+gV9usWd+ayntWSzpAHTFscfao1TxLVd1OgwmtMattb0CFKbOeVjULyIfKFZFQPzQRMAyXaxnVKeVfYUVHsfcy6YV4Vu5xYuVx+ooGLX3yqsIhKjf04lyJaWbJOd2WAv5nTt89DH2Ytiij+fogFcXeHoupLvCVFWGn10vjRnBZr/Bs2sq1mlnEBTKQ62VWTYMmGGfvIDw3lyWcnV2AsvbIll+IlLmYns0vW+17t1iL7cBvaFVo933AZgn+1YXhlCIV4iAbqughWVUNLFNKETQDEin/w7YyM2Zhhw7uzVgGQyiil0WJZKiZqtMl9VaWmpHn15HiU4CZ+Sd4A0Q51Ze+/W3RZxt4ei/+LtCGl6rCaLt4kkAajkF3purY6QSrs3UWM0CEpZnP78/f5lIYjAILKqhz/HDCZQQcaNaDk6iBLtmSoRMDgx3WjAimVyYdqInXH/phJL9U6SyTLp0YfhY+FnXlKJh/8VU8d99Nrus=
  template:
    metadata:
      name: karakeep-secret
      namespace: karakeep
    type: Opaque
