---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgCbDPffK9x1YpaSKaAz3Yne7QRQ82cVf0i7YvOcJooYP5M+vg0iQ/1rjuOOS1esv4MTHxtkNdLpNoiRZifG84n3M+RFn68x9TZREDze/IXzN+oprx5oOT9N3suFoZE9yxws2WCkC83OyEGs43LkJwZS6N96VcKXkeuC26l5p0jUYeJT2DaoWIX5LmKQOT6QmN38KKAoQBXoxP2tZx3SKSZXpzIiat4L/phwgxoAMu5B4JiU9FFPyWFxhL5KB4MUZs5Ij8TGiU4nUdeglDzHqfzwezXY86TNQXVC2VFiTc8Zh1T1hFnP++3uLC79IjhS1Odo2xrDPZd8KioIKk50shx6GaMXkCK5GUsRAEvp3+/fT57N/iaN9HFX7YsgK9noYe6gWHeHAvQ7OFEgLCpA9Wi5LmzUZzZiVspzgCqRb7OZZ7SOZhg7jMRPhu0DhV2cXraGDLMPdAIJdgr4FWVWXxOYQ7XTcpsBSUsHRLnTW2+3U1W/jtdSMJNMnU3SD9gvVKfxL48LRrnJbbc7A6hw4W4P5EoMyV3roC/KvHehDqzhT7GMWmvDGxUza6U67JUK8cRT2RxhS0Fc61FFJLVercf3k2ge9dRt5prC+4nTvRvOGrY+LgtctIFeYQmsivJcbaJsFJn8EchATdfBVbpbHlwJMhcrP22sZmOEYhE+kLusGTcoZAH11WYYVQUEG2CbgNksqHZFEK5fgBIK6p635B2vBFyd3LvcPo8RYO7TOuAjbQ7/u86kWsXj7GPUtkQOrqc=
  template:
    metadata:
      name: karakeep-secret
      namespace: karakeep
