---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring
  interval: 10m0s
  path: ./flux/monitoring/config
  prune: true
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
