apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podmonitors.yaml
  - prometheusrules-flux.yaml
  - prometheusrules-longhorn.yaml
  - prometheusrules-crowdsec.yaml
  - longhorn-servicemonitor.yaml
  - prometheusrules-traefik.yaml
