apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-rules
  namespace: monitoring
spec:
  groups:
    - name: flux
      rules:
        - alert: FluxReconciliationFailure
          expr: |
            max by (exported_namespace, name, customresource_kind) (
              gotk_resource_info{ready="False", suspended!="true"}
            ) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Flux {{ $labels.customresource_kind }} reconciliation failure"
            description: >-
              {{ $labels.customresource_kind }} {{ $labels.name }} in namespace
              {{ $labels.exported_namespace }} has been failing to reconcile for
              more than 10 minutes.
