---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system

resources:
  - network-policies
  - metrics-server-release.yaml
  - cilium-release.yaml
  - longhorn-release.yaml
  - sealed-secrets-release.yaml
#  - network-testing
#  - metallb-release.yaml
