---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system

resources:
  - longhorn-release.yaml
  - backup-secret.yaml
#  - backup-target.yaml
