---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgACrxBTRhr98Nhy1Vc/Bg9yyExfAWlETN19QP+ie8pCVYSeKgVAjshb04JJcGG5BOODwpmfprJ9qHHCLUqltkDrt2/4wjaNi/j0O+cilHdk+JnJkvqTHZdBYduC8DfWqTQk5cUtiAEjCzU8uVR7LmJF10fu+VBlE5RPcI5CDanDNJVriIb/8RuNsLucHz+5bVXNzKSqnLkKiLyxp+/gPskMuu/SZCTHO4BrRLKRcldMhlxJ7m9vM+EkIxjx8r9d5Rn+bb892I0gjqUXWgSL2tsJ7IQ6P5QBSSrNjAYv9KWtIomNRFYflS3zNKCUSDXxEOWQ97ci7uOKJEXHA/2ywM7eGGcQ8Y2+Mjuf1Y1b+TClUqhuXrvhsnSjvd2LDw8v8PrqVqTv06vNP/Sa01f8sbxvHDV4hn0oF/w68GhKj+BEDAy+jNfrqrgRgbMlPuXP2ANW9nMx23V+Vif/cqo9zAKTSbG91hTO751M4JxeSUKVCZpIAF9eszXyCBokgYny8WZf7BFtNYOtfj+F8DH/cFm1jVXRs7UzZxBN/BC/Y9bWrgthM+ulqPwq/JO35aPG1Ap01NvdU9EY7/1QaSES5iPH4/5I7GLoW6GUsKJwkCq89i+GEsE7gCPp/RdP6ItU48+l/+4LyK3TpKrwkjMk4MihtfKyE/LewsN/Re6I14fjNEf/fAqHGVermV6AzqoEF3YhKnWxyo2T5ivSg9vUKW4NBG5ZF8oZv7TqWR8jyjSXQznjq7ZygP8UJ3fv1FHe/oDNxyvRJcXVsnsD1ps=
  template:
    metadata:
      name: postgresql-secret
      namespace: authentik
    type: Opaque
