---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: authentik
spec:
  encryptedData:
    password: AgAJAHa/rdjJQm+WCI+MrmO6EAjogw8TvSwiHoHnoNt1WK1AWqr4nDAvwqOxZaodCIA1haNsIZ7wuNw6L5N9a7AkmXim5O7rese+ugOLBeyWJOedIQAdkC9fqOojKZ5AYTd6y+/Yz2/DU7FxGuP0tjDRKDPojSuqfWWZd3+TFLM1qvFDokRzLBmHI7vq4sNrrygcNFfxJhrF4Bi5JFvO1y1dKFaetl5BRsiK8o9Vz9PsnTG37J3s6AN3kv9O20TEFfN7PteaBCAA/P+LdkthDdDXu/pPn7C5m1h4A3lGHs+JWE3paWNu4PKfbJ/lV7ocJhpCvn2iJqbcoXJSdCB9mKuPxTx9IyZS1dkMdOAiP3WP70MK7HCl7+U6yHVxxNXVXwvhBRPEfrocAQUb4Ni554kssnGJIIiJic+zOKjr2lQVGzoxf40AydAvLeRmeDogWez8n+OE5fzgBA6CzZYvUxjg7jmmCXCdXh4f0BK+7+tyZyCqR2pcdLAUwspeAx1/0B56Vrjp5iP+SwKiH77BS77mckw53V0Nn8NAHgTBe5KHQn20IScnf+fT2kuxLhUTmr23zkHmWatviHT+M5Dna9bAkaucR+ORZZn7hSFc1ZzH2SVNv3VUSgO/+TewKuXILIhaR5HINzHTcHT7TufHxZX9XeRU0b711LmZ7LNJ39RyKi+aZLdWxKiFVdFFgG0HXlqnbaK6M8LtMLQSpW5eSUf9OIDPoUtilLJLBul7kqoJVaRQFd1R4lY+6mwLtC6xARg=
  template:
    metadata:
      name: postgresql-secret
      namespace: authentik
    type: Opaque
