---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: donetick-secret
  namespace: donetick
spec:
  encryptedData:
    DT_JWT_SECRET: AgAY/K+FMmTWnQaV1AyzT3mqBOlMEdkpi/r79fAxMulyllz12RxSY2/UIGJpr0F+zuu3Qmzlgp7w0W8lXVKF8R6/NRYbUXLFz1VauAjIvVm3LooeO/dI+4kqYOFXyV2duYVSaobfhgIbBSgU3BGelNTrHK7Zo3MtynwbwQbN6a7dVh+R9G0EuwkPL7FdzyGy1PE9/4NacB8OFN6cElk0Gzw3TMEHDT5Ejv/lhnrAivA/ld5iw336KjVEnfFaUzcX6q26AQ5dX5mqN6pzKvWQkGkOn+ayRsUz8ZxzttLjil95BeZq/8VR508PVG+XzWpwru2F4+TQRnWKcLSorcUML4XXwiLV0NmQ8aKcyHTQYA9ms+P+E20L4p3wUOnTov9lWCSgRFamLIoaSlZhHWOH+Pk0ArqGvyFt3Nd2Gi6GhEGoGnriFtvosmOymytqJuHummRSDyfVOx0CDD7EETuXVMIyccOpR+1qWD/a9dkxgaGTkP8NGXT5HBMeaEB/IyL8NnAPc3kBafYPfNe1UA3r9628M8lwPXrlUiv+Ng+mPqxUlNmX9moXVZexmv8+uwnPZTPHRb9aAVge/TWhieJ22Gfk9+4CIbTpOenMiddaAfG1hkx1y9VbBXTIya0hZdfuhtDqGi/qUFGZ38/H/IgoGv02x4/uUbbJKFRgOhhEHOIphYUmH0gRJiKNLScKbqxcgNQnA/S9RoxuS202QW6mdWCmmIF301wmYosYuD58AfJM24oMIyWoq248j4vUrjUUQUQXz1lvMgj4eZSgSkt/2NAcg2H03zy5Hakxz5XlwtYOHXupkp66lWLoa+nTdojgrThlMHAR73dua1tWL/DemyZvpYhPOEvUbtSKmTgZ3ee5wNL6e6Egwv+jEwH4m/u1LRsxzN76WL4+uWXUDxAQC0aMIZajpYF6+zsjB6mW
  template:
    metadata:
      name: donetick-secret
      namespace: donetick
