---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dns-porkbun
  namespace: traefik
spec:
  encryptedData:
    api-key: AgBWhBLd4KDkQtEhe/fz3kukgYWE7hZbTKG2e7YT5tkFPfZ+AJZUWV41fdx3Dlp7l1tob9h7QInFwvwLbmlm8BpVkhaBa80WDeazamOuNQ24R3+416t6z26iPp6RxhANggzjHHP0Lu2cyyRBvLmPR7hKj0uKNUJ6EQ3ddY7vMcMn9u7Gdld8dsEQHbL3hzaiQBNfaPM9DhNL+z5xd51UruZP3CVlmhKIcOlnU6QU3r3pJ1vXA+vwrwiORcGiBAFbflhYn5j2TSqRovmE+J3Rct1mbLkywfve9V2EfsfCTPO8gZvcVlUHoNJAk7WAQQ/RyNSx+DRp8NZC8Vad5fJb4KQP9l8JHzoSeetUSW34MF8JiRgZrFMbC270pGh8CfX0k2+L0rG8W5UzUJiPCYOFRVKMJ92XE55+z36e6DOeMrhI9JOuyA3g+rcVwliGzKnjzBeLqyE33axJbeU2l+k/3yAMwULDlo8c9wgkMziIBwuUo3lY3UqNQ4KdbPt1YD5r9aErasqYs0t+Gc4xVWaVnDDWT/qwqMn6bxdXbrZGQxyTNAJzTH5Lsoj+c9h+hJDKOSigf2c50opg9/Hpg4Yea/GecuxZd7xA67CCHtAis7td9PW/VfCJBgq4/m9Jm8JpYCPo2HrFUMDCUtTgICUIPU1UqJywCZJHGLASgbA0WQu8whISZ9r5FyrKfS/i1rwg8qLJcdNY60B6frHxzZThYklQfJcHxsnQFUtZXGHjcaZHRDH9HXQIPuTrUYHHOk6CN88IWDE9yebP24jQ6y98cLLo7Um76A==
    secret-key: AgCkQHGuAB1z2/WlnwKXIUcrQeToQFuEeclvWzhWZMyc+jAiFnzwALJOZvqMTUDesizO5JcIqPkOIAG7nZ6lgqhKajdEIgz6UCaiWB8kx8IpCZT21hNdGCQ9M8TCeg4gWY+ne9N6iaIl9ktjuHw18And41r4npRwVj4MKKMzAuLlieucNUdOYNnE3JsZvCdzFWSabb2arqYDW6FpsKBQFnW95Gu7FCaOVL8w3ub7cQ1+UQZ3yNwUq1x1esUaQob8l/3LbZbhEHBZizZynKV4DhSNrij4f4qmjNKwFqMc4hHcJiARkRzQg2LCcBV5YQ0lECwxoCgdp4vlHcIQHcM1+t6TCsVR1rYQxMOkW0es808gqq0INEifJWXle1yI0RK+FBUtfK2HwZXysdlzxuDqkzBOqP4msV08r4v10rXLvmqUpChPUBpkr1w/umwD1GwLUb4z+mv9gU25kT4kPqzwzasVejzZg8VXDl2lajRHCPixsCtw0+FyI6Cy7M0L0eaSrnNbqjW3T5c/QYzH4PFj2d1N4+zMpoQXCjC/irIqphlbHx0xj3sy84RBzUHsWtk74smdVjCM+rqEGgDe7aI/WmEHLnYfVP8FNGSnHvqug66dctOSi2bYwRxupS8PpxTkCsz86o0ImwNvDuACyevTaA9nJkxuDrpYJ41oxt33qK+7igb8jLlDMGN1e7jgjoK+ZiRpVRCivXx8JDIGy7afhJOPiX01w/1kRRqKYCG0uioYKY7D+zeLVPOLSscEJMiIkUSBcrXsQrO3t2TqE/85ikDVwgK60A==
  template:
    metadata:
      name: traefik-dns-porkbun
      namespace: traefik
    type: Opaque
