---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-dns-porkbun
  namespace: traefik
spec:
  encryptedData:
    api-key: AgCLSzNDQ49lcwn8eFCigF4FLhoMtmLvvDBHG7Y9bR/sXWq9AyB4rsfsZrPs/M7n7IiZMfVajrmdCHq4mJmvemKgXUcLXQks2fHmNDhHSG6iRhwFXh+Zpr91teNBkaTIqbUAfLkqvQR4Al4u0VFGCBVRDFjZn7GZPil7x6NyNUMDgFqSMFrFtO9UPR+W+eTim2vjc1gYlQvu+pX40XxVmaAPWZ0eZExaTP2vTtpfyA8nYUIhBbGDNJ/gCfj6HBmlvQQv1fSy+CGwwArQ95v2j9WSq6f+hpTBoTo9387i6+kaBXHY7VtXk0at23ZqDeGgkwngGau25lCAGfLTNDMGKajSzNkk70jWxKY994nR4TR3AxBCTUL+DSctfFDjB4+J2RC7o+7aU0mYyLb5Qff0p/gFcpkKuPC0l/jlHD2CYlCJxgoo5ssGFjiroLoOrq29ROLzVbVd7sXjNmRmxz9bTr5BfQi2Dq+1EqzEbfY9c5V9qaCZrstuHgURfNFdAo4Ijxr0D3D63kSS6/ZqIfSAbnfNHy6tgmaEEbRjwCCKWrvz2IbVru63lSqMYjHycsTbMlUSV0Wloc7vlNpspX/3PIz/6aAvrNryAyE9q4L0wgHZ4Ui7jr7yON180BAoaeVU+eDfiGGA4VNtCe+qQavTwz+WM5LxbK36/FWC08Nk4lSQ0uiT1LtTP8GO/dUqT4Q4RPtHu4MpowK9545TTBqPWXrUjyID3gAO8k/SkqSwPAUVq8t5p6/cukkjLUY4qMqdtREPp1ZWZ7CZXrnV7SxNF1Ba7L8Piw==
    secret-key: AgAeCFxdM17Hd/m2MvQWe7Ymjmd2fFKPSpi0pvc8EKTlwgFoHiyEsnhTq6ytWJKC/B4u4l1Jv0v91BubyzY8ihRaNXxbu8a7zMwy1X32Ax3CbjgHkXMV62Q18ie7RvgCEWaBbVsvOFOy2Zo8QcgXc3PQguawtfjbe9oO5+/njZmRyW5sDcj8V7C/VW4gyEJsBImh8sNtbnmQGud++y2w8xfW5yD8OkeEPkJ0nnwCLWoFjWrLUiaUfC5+mXqmRQBa7RTVFZ2G2etWxzdbjzZwloB8ZG9Mk+otWiy7n28pXCzHa1GEc+18XNwGLtwuo1WhmDCwenztTU2rN527X+kWSGpp8zP+DcDaY4/fOADPQq9pB1fYAyHL809o4LmZd6UfljTJb9iGuRm+cSS1G3EySgvmm196WnmKMeOE3vcXquVw3/hLB/CLP92m8mYmRBJq82mDRbW55jDK6db2jQWFULWjqDec+8WZ13fQ2OsmYLtg/P+tLEmuAj9U6lC+Fr+u/ONPq2nYAZjJ/9Wi+ACCvr+e07ObZznPEztZ2qF8a4z7OShOESxWBJFEORp2ZjJlUJVRfyRKNWnHszwC5ekB/5gicFn511ecHWjD9kOzs9IbMZPe+yE8/m9qOU/cGlnbLdt/luKw+UmCL9AMXyueafPHtAvShdFqIl+lrE/9/D5nZcLWkC4D5+FhKbN3C4TPJa9yNs0i5A2IF5PnxShmEX3JcfW3MaScEeIqBtqSNX+Wgf5ELkCC8cHT8Ddl4xHv/izszlz4HaS0g2iVRhl1ZEYKEsAu0Q==
  template:
    metadata:
      name: traefik-dns-porkbun
      namespace: traefik
    type: Opaque
