---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia-secrets
  namespace: authelia
spec:
  encryptedData:
    users_database.yml: AgCsU+00ZgZIaVlhUpPMR0y4KH8up0T4GBdSUsD9mEB79Nc8QWQsLlHrHLpJIkL2bCOn6KfN9KxEUSBW8e4SG3mQpuhv7rqf7tB9m+fQ6MIBvkD/5cD3t5DRyPY79reBacycQ45cS5nJBKt8hleX70SXOpH/N9PbircVgcRFOTz38bTrs6SJDvO06ymJrzC/2buprj+RQU+rQtC8P9UzOrSncHpfcuUmm2lyrPggDEPU4A/eQ2rohsaSg32uErQIFlRnEBvLIc8RN8cc1AYwfstmeBEUrUJNd+mXUU5jbVVv9fCtw1Ksse8+wS6rQutWUjWvRaDmBFAMMoRDufVwhfJRj+09YRuGZbQmTFc95EVLHst3L0k7wbAyFkEhDmnFezpQdh2lYgBrX4VOMYOlW9R1A/KUyxcKv8PWPmPvctIRyUO9QKzV+d44iHGAMAv/ugZox8BZf9coAChplGy9G2kybwh2dlzWKWm9dgAnvyVJB2eeAr0MvNxNmscY1TcQwGvueeQ/cDsQyw4D5lSkRPhIAppZtqF4KQGgoGkPxQk/m4tuxQDVnDVf7P0DwTP5tZ7v7mvu9TFnPl37Vo0uv01h7roCzrM3GgFrNH6c65xN1FQKOTBuonMjbVkERub6iKo09JSF3cknvruITFhQLCltYW6j1+8qu9cIlMd/MlUy6VPYGQ57cWBGqz5AC3b1ZIv/ch17sezxJy428fzcPE3nYNtd1gJ7nS9CkJJA0k9dpW85fTRekApDf7Ku5sL6HsPmG3P3STOAGMEuBseQGRtiY9SypoPOmqXVebovxEfPPCQn9s2C9kJxNutDhUGeeqkw4Y7ZYniuGiRlMur4XLBWda5K0A4PLiBdOSuuCqSKdlpcr1XSs96YNjIilDYnwRCDyGNLr3b0u5trVBU5aA0TsfgPavYp5S6h3ckRNYOwDHekHs2pJbSqvnIWk7P1z0jZQ6KShw5kfBWg5AUwznEMGKwfk1ld+ze6vQv5GLgUl0Z3Hc5Q
  template:
    metadata:
      name: authelia-secrets
      namespace: authelia
