---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv.yaml
  - authelia-release.yaml
  - ingress.yaml
  - network-policy.yaml
  - authelia-sealedsecret.yaml
