---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: s3://longhorn-bucket@garage/
  credentialSecret: backup-secret
  pollInterval: 5m0s
