---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure/releases/flux-kustomization.yaml
  - infrastructure/config/flux-kustomization.yaml
  - monitoring/flux-kustomization.yaml
  - dmz/flux-kustomization.yaml
