---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik
  namespace: metallb-system
spec:
  addresses:
  - 192.168.123.21/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: traefik
  namespace: metallb-system
spec:
  ipAddressPools:
  - traefik
  nodeSelectors:
  - matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole
  namespace: metallb-system
spec:
  addresses:
  - 192.168.123.22/32

---
# Restricted to control-plane: only node with a 192.168.123.x interface, so only
# node that can respond to ARP for this IP on the home LAN.
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole
  namespace: metallb-system
spec:
  ipAddressPools:
  - pihole
  nodeSelectors:
  - matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
