---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: s3
  namespace: longhorn-system
spec:
  backupTargetURL: s3://longhorn-bucket@garage/
  credentialSecret: backup-secret
  pollInterval: 1h0m0s
