---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-secret.yaml
  - backup-target.yaml
  - longhorn-volumeattributesclass-rbac.yaml
  - volumesnapshotclass.yaml
  - recurring-jobs.yaml
  - recurring-job-backfill.yaml
